apiVersion: v1
kind: Pod

metadata:
  name: dev-pod
  namespace: dev
  labels:
    app: dev-pod

spec:
  containers:
  - name: dev-container
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: dev
spec:
  selector:
    app: dev-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
