apiVersion: batch/v1
kind: Job
matadata:
  name: simple-job

spec:
  template:
    metadata:
      name: simple-job
    spec:
      containers:
      - name: simple-job
        image: busybox
        command: ["echo", "Hello Kubernetes!"]
      restartPolicy: Never
