apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedulejob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: container1
            image: ubuntu
            command: ["bin/bash", "-c", "sudo apt update; sleep 30"]
          restartPolicy: Never
