apiVersion: v1
kind: Pod

metadata:
  name: studentpod
  labels:
    app: studentapp

spec:
  containers:
  - name: database
    image: mayurgg7756/database:17
    ports: 
      - containerPort: 3306
      
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "1234"
      - name: MYSQL_DATABASE
        value: "studentapp"
      - name: MYSQL_USER
        value: "mayur"
      - name: MYSQL_PASSWORD
        value: "1234"
  
  - name: backend
    image: mayurgg7756/backend:17
    ports: 
      - containerPort: 8080
  
  - name: frontend
    image: mayurgg7756/frontend:17
    ports: 
      - containerPort: 80
      