apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: replica_set
  labels:
    app: replica_set

spec:
  replicas: 5
  selector:
    matchExpressions:
    - {key: nginx, operator: In, values: [nginx-app, replica_set], namespace: default,}

  template:
    metadata:
      labels:
        name: nginx-app
        app: nginx-app

    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP

