apiVersion: v1
kind: ReplicationController

metadata:
  name: replication-controller
  labels:
    app: replication-controller

spec:
  replicas: 5
  selector:
    app: replication-controller

  template:
    metadata:
      labels:
        app: replication-controller
        name: nginx-app
      spec:
        containers:
        - name: nginx-app
          image: nginx:latest
          ports:
          - containerPort: 80
            protocol: TCP
