apiVersion: apps/v1
kind: ReplicationController

metadata:
  name: replica-controller
  labels:
    app: replica_controller

spec:
  replica: 5
  selector:
    matchExpression:
    - {key: nginx, operator: In, values: [nginx-app], namespace: default,}

  template:
    metadata:
      labels:
        name: nginx-app
        app: nginx-app

    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP

