# Create a POD and NodePort service for it.

apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod
  labels:
    app: nginx-app

spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP


---
apiVersion: v1
kind: Service

metadata:
  name: node-port

spec:
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

