apiVersion: v1
kind: Service

metadata:
  name: mysrvices

spec:
    type: NodePort
    selector:
      app: myapp
    ports:
      - protocol: TCP
        port: 80
        name: nginx
        targetPort: 80
      - protocol: TCP
        port: 8080
        name: tomcat
        targetPort: 8080