apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment
  labels:
    app: deployment-app

spec:
  selector:
    matchLabels:
      app: deployment-app
  replicas: 5
  template:
    metadata:
      name: deployment
      labels:
        app: deployment-app
    spec:
      containers:
      - name: deployment
        image: nginx:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  selector:
    app: deployment-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
