apiVersion: apps/v1
kind: statefulsets

metadata:
  name: mysql-stateful
  labels:
    app: statefull

spec:
  selector:
    matchLabels:
      app: statefull
  replicas: 5
  template:
    metadata:
      labels:
        app: mysqlapp

    spec:
      containers:
      - name: mysql
        image: mysql:latest
        port:
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
