apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-app
  label:
    app: frontend-app-advanced
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app-advanced
  template:
    metadata:
      labels:
        app: frontend-app-advanced
    spec:
      containers:
      - name: frontend-app
        image: frontend-app:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service

metadata:
  name: loadbalancer
  label:
    app: frontend-app-advanced

spec:
  selector:
    app: frontend-app-advanced
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

