apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
  labels:
    app: database
spec:
  serviceName: "database"
  selector:
    matchLabels:
      app: database

  replicas: 3
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mayurgg7756/database
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "studentapp"
        - name: MYSQL_USER
          value: "mayur"
        - name: MYSQL_PASSWORD
          value: "1234"

