apiVersion: v1
kind: Service

metadata:
  name: mysrvices

spec:
    type: NodePort
    selector:
      app: studentapp
    ports:
      - name: nginx
        protocol: TCP
        port: 80
        targetPort: 80
      - name: backend
        protocol: TCP
        port: 8080
        targetPort: 8080
      - name: database
        protocol: TCP
        port: 3306
        targetPort: 3306